OPENAI_API_KEY ="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"
OPENAI_MODEL = "gpt-5-mini"
